local _G = _G;
local ABGP = _G.ABGP;

local pairs = pairs;
local ipairs = ipairs;
local type = type;

_G.ABGP_Data2 = {};

ABGP.initialData = {
	itemValues = {
		timestamp = 1596567506, -- https://www.epochconverter.com/ or GetServerTime() ingame
		data = {
			{
				"Barrage Shoulders",
				0,
				"|cffa335ee|Hitem:21699|h[Barrage Shoulders]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Breastplate of Annihilation",
				200,
				"|cffa335ee|Hitem:21814|h[Breastplate of Annihilation]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Metal Rogue",
					"Paladin (Ret)",
				},
				"GOLD",
			},
			{
				"Beetle Scaled Wristguards",
				0,
				"|cffa335ee|Hitem:21708|h[Beetle Scaled Wristguards]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Leggings of Immersion",
				0,
				"|cffa335ee|Hitem:21698|h[Leggings of Immersion]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Boots of the Fallen Prophet",
				0,
				"|cffa335ee|Hitem:21705|h[Boots of the Fallen Prophet]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Boots of the Redeemed Prophecy",
				0,
				"|cffa335ee|Hitem:21704|h[Boots of the Redeemed Prophecy]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Boots of the Unwavering Will",
				0,
				"|cffa335ee|Hitem:21706|h[Boots of the Unwavering Will]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Amulet of Foul Warding",
				0,
				"|cffa335ee|Hitem:21702|h[Amulet of Foul Warding]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Pendant of the Qiraji Guardian",
				0,
				"|cffa335ee|Hitem:21700|h[Pendant of the Qiraji Guardian]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Cloak of Concentrated Hatred",
				200,
				"|cffa335ee|Hitem:21701|h[Cloak of Concentrated Hatred]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"KAT4FITE",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Ring of Swarming Thought",
				0,
				"|cffa335ee|Hitem:21707|h[Ring of Swarming Thought]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Hammer of Ji'zhi",
				0,
				"|cffa335ee|Hitem:21703|h[Hammer of Ji'zhi]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Staff of the Qiraji Prophets",
				0,
				"|cffa335ee|Hitem:21128|h[Staff of the Qiraji Prophets]|h|r",
				"Ahn'Qiraj",
				"The Prophet Skeram",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Guise of the Devourer",
				250,
				"|cffa335ee|Hitem:21693|h[Guise of the Devourer]|h|r",
				"Ahn'Qiraj",
				"Bug Trio",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Ternary Mantle",
				250,
				"|cffa335ee|Hitem:21694|h[Ternary Mantle]|h|r",
				"Ahn'Qiraj",
				"Bug Trio",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Cape of the Trinity",
				0,
				"|cffa335ee|Hitem:21697|h[Cape of the Trinity]|h|r",
				"Ahn'Qiraj",
				"Bug Trio",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Robes of the Triumvirate",
				0,
				"|cffa335ee|Hitem:21696|h[Robes of the Triumvirate]|h|r",
				"Ahn'Qiraj",
				"Bug Trio",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Triad Girdle",
				150,
				"|cffa335ee|Hitem:21692|h[Triad Girdle]|h|r",
				"Ahn'Qiraj",
				"Bug Trio",
				{
					"Metal Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Angelista's Touch",
				150,
				"|cffa335ee|Hitem:21695|h[Angelista's Touch]|h|r",
				"Ahn'Qiraj",
				"Bug Trio",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Vest of Swift Execution",
				200,
				"|cffa335ee|Hitem:21680|h[Vest of Swift Execution]|h|r",
				"Ahn'Qiraj",
				"Lord Kri",
				{
					"KAT4FITE",
					"Metal Rogue",
				},
				"GOLD",
			},
			{
				"Ring of the Devoured",
				0,
				"|cffa335ee|Hitem:21681|h[Ring of the Devoured]|h|r",
				"Ahn'Qiraj",
				"Lord Kri",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Petrified Scarab",
				0,
				"|cffa335ee|Hitem:21685|h[Petrified Scarab]|h|r",
				"Ahn'Qiraj",
				"Lord Kri",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Wand of Qiraji Nobility",
				0,
				"|cffa335ee|Hitem:21603|h[Wand of Qiraji Nobility]|h|r",
				"Ahn'Qiraj",
				"Lord Kri",
				{
					"Garbage",
				},
				"SILVER",
				"Non-Touch of Chaos Prio",
			},
			{
				"Angelista's Charm",
				0,
				"|cffa335ee|Hitem:21690|h[Angelista's Charm]|h|r",
				"Ahn'Qiraj",
				"Vem",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Gloves of Ebru",
				0,
				"|cffa335ee|Hitem:21689|h[Gloves of Ebru]|h|r",
				"Ahn'Qiraj",
				"Vem",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Ooze-ridden Gauntlets",
				0,
				"|cffa335ee|Hitem:21691|h[Ooze-ridden Gauntlets]|h|r",
				"Ahn'Qiraj",
				"Vem",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Boots of the Fallen Hero",
				175,
				"|cffa335ee|Hitem:21688|h[Boots of the Fallen Hero]|h|r",
				"Ahn'Qiraj",
				"Vem",
				{
					"Metal Rogue",
					"Tank",
				},
				"GOLD",
			},
			{
				"Mantle of Phrenic Power",
				100,
				"|cffa335ee|Hitem:21686|h[Mantle of Phrenic Power]|h|r",
				"Ahn'Qiraj",
				"Princess Yauj",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Mantle of the Desert's Fury",
				0,
				"|cffa335ee|Hitem:21684|h[Mantle of the Desert's Fury]|h|r",
				"Ahn'Qiraj",
				"Princess Yauj",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Mantle of the Desert Crusade",
				0,
				"|cffa335ee|Hitem:21683|h[Mantle of the Desert Crusade]|h|r",
				"Ahn'Qiraj",
				"Princess Yauj",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Bile-Covered Gauntlets",
				0,
				"|cffa335ee|Hitem:21682|h[Bile-Covered Gauntlets]|h|r",
				"Ahn'Qiraj",
				"Princess Yauj",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Ukko's Ring of Darkness",
				0,
				"|cffa335ee|Hitem:21687|h[Ukko's Ring of Darkness]|h|r",
				"Ahn'Qiraj",
				"Princess Yauj",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Creeping Vine Helm",
				200,
				"|cffa335ee|Hitem:21669|h[Creeping Vine Helm]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
				},
				"SILVER",
				"Druid super-priority, catch-up",
			},
			{
				"Necklace of Purity",
				0,
				"|cffa335ee|Hitem:21678|h[Necklace of Purity]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Robes of the Battleguard",
				0,
				"|cffa335ee|Hitem:21671|h[Robes of the Battleguard]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Gloves of Enforcement",
				200,
				"|cffa335ee|Hitem:21672|h[Gloves of Enforcement]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"KAT4FITE",
				},
				"GOLD",
			},
			{
				"Gauntlets of Steadfast Determination",
				175,
				"|cffa335ee|Hitem:21674|h[Gauntlets of Steadfast Determination]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Thick Qirajihide Belt",
				150,
				"|cffa335ee|Hitem:21675|h[Thick Qirajihide Belt]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Leggings of the Festering Swarm",
				100,
				"|cffa335ee|Hitem:21676|h[Leggings of the Festering Swarm]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Scaled Leggings of Qiraji Fury",
				0,
				"|cffa335ee|Hitem:21668|h[Scaled Leggings of Qiraji Fury]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Legplates of Blazing Light",
				175,
				"|cffa335ee|Hitem:21667|h[Legplates of Blazing Light]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Paladin (Holy)",
				},
				"SILVER",
				"0 cost if bwl pants already",
			},
			{
				"Recomposed Boots",
				0,
				"|cffa335ee|Hitem:21648|h[Recomposed Boots]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Badge of the Swarmguard",
				300,
				"|cffa335ee|Hitem:21670|h[Badge of the Swarmguard]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Hunter",
					"KAT4FITE",
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Sartura's Might",
				300,
				"|cffa335ee|Hitem:21666|h[Sartura's Might]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Silithid Claw",
				0,
				"|cffa335ee|Hitem:21673|h[Silithid Claw]|h|r",
				"Ahn'Qiraj",
				"Battleguard Sartura",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Mantle of Wicked Revenge",
				200,
				"|cffa335ee|Hitem:21665|h[Mantle of Wicked Revenge]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"KAT4FITE",
				},
				"GOLD",
			},
			{
				"Pauldrons of the Unrelenting",
				0,
				"|cffa335ee|Hitem:21639|h[Pauldrons of the Unrelenting]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Cloak of Untold Secrets",
				0,
				"|cffa335ee|Hitem:21627|h[Cloak of Untold Secrets]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Robes of the Guardian Saint",
				200,
				"|cffa335ee|Hitem:21663|h[Robes of the Guardian Saint]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Silithid Carapace Chestguard",
				0,
				"|cffa335ee|Hitem:21652|h[Silithid Carapace Chestguard]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Scaled Sand Reaver Leggings",
				300,
				"|cffa335ee|Hitem:21651|h[Scaled Sand Reaver Leggings]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Metal Rogue",
					"Paladin (Ret)",
				},
				"GOLD",
			},
			{
				"Hive Tunneler's Boots",
				0,
				"|cffa335ee|Hitem:21645|h[Hive Tunneler's Boots]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Ancient Qiraji Ripper",
				400,
				"|cffa335ee|Hitem:21650|h[Ancient Qiraji Ripper]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Metal Rogue",
					"Slicey Rogue",
				},
				"GOLD",
				"Non-CTS Prio",
			},
			{
				"Barb of the Sand Reaver",
				0,
				"|cffa335ee|Hitem:21635|h[Barb of the Sand Reaver]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Hunter",
				},
				"GOLD",
			},
			{
				"Barbed Choker",
				100,
				"|cffa335ee|Hitem:21664|h[Barbed Choker]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Hunter",
					"Metal Rogue",
					"Paladin (Ret)",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Fetish of the Sand Reaver",
				200,
				"|cffa335ee|Hitem:21647|h[Fetish of the Sand Reaver]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Libram of Grace",
				0,
				"|cffa335ee|Hitem:22402|h[Libram of Grace]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Totem of Life",
				0,
				"|cffa335ee|Hitem:22396|h[Totem of Life]|h|r",
				"Ahn'Qiraj",
				"Fankriss the Unyielding",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Gauntlets of Kalimdor",
				0,
				"|cffa335ee|Hitem:21624|h[Gauntlets of Kalimdor]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Gauntlets of the Righteous Champion",
				0,
				"|cffa335ee|Hitem:21623|h[Gauntlets of the Righteous Champion]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Slime-coated Leggings",
				0,
				"|cffa335ee|Hitem:21626|h[Slime-coated Leggings]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Sharpened Silithid Femur",
				450,
				"|cffa335ee|Hitem:21622|h[Sharpened Silithid Femur]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
				"Non-Shadow Flame Prio",
			},
			{
				"Ring of the Qiraji Fury",
				100,
				"|cffa335ee|Hitem:21677|h[Ring of the Qiraji Fury]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Metal Rogue",
					"Tank",
				},
				"GOLD",
			},
			{
				"Scarab Brooch",
				50,
				"|cffa335ee|Hitem:21625|h[Scarab Brooch]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Idol of Health",
				0,
				"|cffa335ee|Hitem:22399|h[Idol of Health]|h|r",
				"Ahn'Qiraj",
				"Viscidus",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Qiraji Bindings of Command",
				"T",
				"|cffa335ee|Hitem:20928|h[Qiraji Bindings of Command]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"GOLD",
			},
			{
				"Conqueror's Greaves",
				300,
				"|cffa335ee|Hitem:21333|h[Conqueror's Greaves]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Conqueror's Spaulders",
				300,
				"|cffa335ee|Hitem:21330|h[Conqueror's Spaulders]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Deathdealer's Boots",
				300,
				"|cffa335ee|Hitem:21359|h[Deathdealer's Boots]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Deathdealer's Spaulders",
				300,
				"|cffa335ee|Hitem:21361|h[Deathdealer's Spaulders]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Footwraps of the Oracle",
				300,
				"|cffa335ee|Hitem:21349|h[Footwraps of the Oracle]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Mantle of the Oracle",
				300,
				"|cffa335ee|Hitem:21350|h[Mantle of the Oracle]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Striker's Footguards",
				300,
				"|cffa335ee|Hitem:21365|h[Striker's Footguards]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Striker's Pauldrons",
				300,
				"|cffa335ee|Hitem:21367|h[Striker's Pauldrons]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Command",
			},
			{
				"Qiraji Bindings of Dominance",
				"T",
				"|cffa335ee|Hitem:20932|h[Qiraji Bindings of Dominance]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Avenger's Greaves",
				250,
				"|cffa335ee|Hitem:21388|h[Avenger's Greaves]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Avenger's Pauldrons",
				250,
				"|cffa335ee|Hitem:21391|h[Avenger's Pauldrons]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Doomcaller's Footwraps",
				250,
				"|cffa335ee|Hitem:21338|h[Doomcaller's Footwraps]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Doomcaller's Mantle",
				250,
				"|cffa335ee|Hitem:21335|h[Doomcaller's Mantle]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Enigma Boots",
				250,
				"|cffa335ee|Hitem:21344|h[Enigma Boots]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Enigma Shoulderpads",
				250,
				"|cffa335ee|Hitem:21345|h[Enigma Shoulderpads]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Genesis Boots",
				250,
				"|cffa335ee|Hitem:21355|h[Genesis Boots]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Genesis Shoulderpads",
				250,
				"|cffa335ee|Hitem:21354|h[Genesis Shoulderpads]|h|r",
				"Ahn'Qiraj",
				"Viscidus, Princess Huhuran",
				{
				},
				"GOLD",
				[9] = "Qiraji Bindings of Dominance",
			},
			{
				"Cloak of the Golden Hive",
				125,
				"|cffa335ee|Hitem:21621|h[Cloak of the Golden Hive]|h|r",
				"Ahn'Qiraj",
				"Princess Huhuran",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Hive Defiler Wristguards",
				250,
				"|cffa335ee|Hitem:21618|h[Hive Defiler Wristguards]|h|r",
				"Ahn'Qiraj",
				"Princess Huhuran",
				{
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Gloves of the Messiah",
				75,
				"|cffa335ee|Hitem:21619|h[Gloves of the Messiah]|h|r",
				"Ahn'Qiraj",
				"Princess Huhuran",
				{
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Wasphide Gauntlets",
				100,
				"|cffa335ee|Hitem:21617|h[Wasphide Gauntlets]|h|r",
				"Ahn'Qiraj",
				"Princess Huhuran",
				{
					"Druid (Heal)",
				},
				"GOLD",
			},
			{
				"Ring of the Martyr",
				150,
				"|cffa335ee|Hitem:21620|h[Ring of the Martyr]|h|r",
				"Ahn'Qiraj",
				"Princess Huhuran",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
				},
				"GOLD",
			},
			{
				"Huhuran's Stinger",
				50,
				"|cffa335ee|Hitem:21616|h[Huhuran's Stinger]|h|r",
				"Ahn'Qiraj",
				"Princess Huhuran",
				{
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Vek'lor's Diadem",
				"T",
				"|cffa335ee|Hitem:20930|h[Vek'lor's Diadem]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"GOLD",
			},
			{
				"Avenger's Crown",
				100,
				"|cffa335ee|Hitem:21387|h[Avenger's Crown]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
				},
				"GOLD",
				[9] = "Vek'lor's Diadem",
			},
			{
				"Deathdealer's Helm",
				100,
				"|cffa335ee|Hitem:21360|h[Deathdealer's Helm]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
				},
				"GOLD",
				[9] = "Vek'lor's Diadem",
			},
			{
				"Genesis Helm",
				100,
				"|cffa335ee|Hitem:21353|h[Genesis Helm]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
				},
				"GOLD",
				[9] = "Vek'lor's Diadem",
			},
			{
				"Striker's Diadem",
				100,
				"|cffa335ee|Hitem:21366|h[Striker's Diadem]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
				},
				"GOLD",
				[9] = "Vek'lor's Diadem",
			},
			{
				"Qiraji Execution Bracers",
				150,
				"|cffa335ee|Hitem:21602|h[Qiraji Execution Bracers]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"KAT4FITE",
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"GOLD",
				"KAT4FITE super prio",
			},
			{
				"Vek'lor's Gloves of Devastation",
				0,
				"|cffa335ee|Hitem:21599|h[Vek'lor's Gloves of Devastation]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Royal Qiraji Belt",
				200,
				"|cffa335ee|Hitem:21598|h[Royal Qiraji Belt]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Boots of Epiphany",
				75,
				"|cffa335ee|Hitem:21600|h[Boots of Epiphany]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Ring of Emperor Vek'lor",
				100,
				"|cffa335ee|Hitem:21601|h[Ring of Emperor Vek'lor]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Royal Scepter of Vek'lor",
				200,
				"|cffa335ee|Hitem:21597|h[Royal Scepter of Vek'lor]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'lor",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
				"Femur Prio; Non-Shadow Flame Prio",
			},
			{
				"Vek'nilash's Circlet",
				"T",
				"|cffa335ee|Hitem:20926|h[Vek'nilash's Circlet]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Mage",
					"Metal Rogue",
					"Priest (Shadow)",
					"Tank",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Conqueror's Crown",
				250,
				"|cffa335ee|Hitem:21329|h[Conqueror's Crown]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
				},
				"GOLD",
				[9] = "Vek'nilash's Circlet",
			},
			{
				"Doomcaller's Circlet",
				250,
				"|cffa335ee|Hitem:21337|h[Doomcaller's Circlet]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
				},
				"GOLD",
				[9] = "Vek'nilash's Circlet",
			},
			{
				"Enigma Circlet",
				250,
				"|cffa335ee|Hitem:21347|h[Enigma Circlet]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
				},
				"GOLD",
				[9] = "Vek'nilash's Circlet",
			},
			{
				"Tiara of the Oracle",
				250,
				"|cffa335ee|Hitem:21348|h[Tiara of the Oracle]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
				},
				"GOLD",
				[9] = "Vek'nilash's Circlet",
			},
			{
				"Amulet of Vek'nilash",
				250,
				"|cffa335ee|Hitem:21608|h[Amulet of Vek'nilash]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Bracelets of Royal Redemption",
				150,
				"|cffa335ee|Hitem:21604|h[Bracelets of Royal Redemption]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
				"Paladin Super Prio",
			},
			{
				"Gloves of the Hidden Temple",
				200,
				"|cffa335ee|Hitem:21605|h[Gloves of the Hidden Temple]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Regenerating Belt of Vek'nilash",
				0,
				"|cffa335ee|Hitem:21609|h[Regenerating Belt of Vek'nilash]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Grasp of the Fallen Emperor",
				0,
				"|cffa335ee|Hitem:21607|h[Grasp of the Fallen Emperor]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Belt of the Fallen Emperor",
				0,
				"|cffa335ee|Hitem:21606|h[Belt of the Fallen Emperor]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Kalimdor's Revenge",
				0,
				"|cffa335ee|Hitem:21679|h[Kalimdor's Revenge]|h|r",
				"Ahn'Qiraj",
				"Emperor Vek'nilash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Don Rigoberto's Lost Hat",
				250,
				"|cffa335ee|Hitem:21615|h[Don Rigoberto's Lost Hat]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Burrower Bracers",
				100,
				"|cffa335ee|Hitem:21611|h[Burrower Bracers]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"The Burrower's Shell",
				0,
				"|cffa335ee|Hitem:23558|h[The Burrower's Shell]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Jom Gabbar",
				200,
				"|cffa335ee|Hitem:23570|h[Jom Gabbar]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Hunter",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"GOLD",
			},
			{
				"Wormscale Blocker",
				0,
				"|cffa335ee|Hitem:21610|h[Wormscale Blocker]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Larvae of the Great Worm",
				300,
				"|cffa335ee|Hitem:23557|h[Larvae of the Great Worm]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Hunter",
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Ouro's Intact Hide",
				"T",
				"|cffa335ee|Hitem:20927|h[Ouro's Intact Hide]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"GOLD",
			},
			{
				"Conqueror's Legguards",
				250,
				"|cffa335ee|Hitem:21332|h[Conqueror's Legguards]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"GOLD",
				[9] = "Ouro's Intact Hide",
			},
			{
				"Deathdealer's Leggings",
				250,
				"|cffa335ee|Hitem:21362|h[Deathdealer's Leggings]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"GOLD",
				[9] = "Ouro's Intact Hide",
			},
			{
				"Enigma Leggings",
				250,
				"|cffa335ee|Hitem:21346|h[Enigma Leggings]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"GOLD",
				[9] = "Ouro's Intact Hide",
			},
			{
				"Trousers of the Oracle",
				250,
				"|cffa335ee|Hitem:21352|h[Trousers of the Oracle]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"GOLD",
				[9] = "Ouro's Intact Hide",
			},
			{
				"Skin of the Great Sandworm",
				"T",
				"|cffa335ee|Hitem:20931|h[Skin of the Great Sandworm]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
					"Garbage",
				},
				"GOLD",
			},
			{
				"Avenger's Legguards",
				0,
				"|cffa335ee|Hitem:21390|h[Avenger's Legguards]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"SILVER",
				[9] = "Skin of the Great Sandworm",
			},
			{
				"Doomcaller's Trousers",
				0,
				"|cffa335ee|Hitem:21336|h[Doomcaller's Trousers]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"SILVER",
				[9] = "Skin of the Great Sandworm",
			},
			{
				"Genesis Trousers",
				0,
				"|cffa335ee|Hitem:21356|h[Genesis Trousers]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"SILVER",
				[9] = "Skin of the Great Sandworm",
			},
			{
				"Striker's Leggings",
				0,
				"|cffa335ee|Hitem:21368|h[Striker's Leggings]|h|r",
				"Ahn'Qiraj",
				"Ouro",
				{
				},
				"SILVER",
				[9] = "Skin of the Great Sandworm",
			},
			{
				"Mark of C'Thun",
				100,
				"|cffa335ee|Hitem:22732|h[Mark of C'Thun]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Tank",
				},
				"GOLD",
			},
			{
				"Cloak of Clarity",
				150,
				"|cffa335ee|Hitem:21583|h[Cloak of Clarity]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Cloak of the Devoured",
				150,
				"|cffa335ee|Hitem:22731|h[Cloak of the Devoured]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Eyestalk Waist Cord",
				350,
				"|cffa335ee|Hitem:22730|h[Eyestalk Waist Cord]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
				"Mage super-priority",
			},
			{
				"Grasp of the Old God",
				250,
				"|cffa335ee|Hitem:21582|h[Grasp of the Old God]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Belt of Never-ending Agony",
				300,
				"|cffa335ee|Hitem:21586|h[Belt of Never-ending Agony]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"KAT4FITE",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"GOLD",
			},
			{
				"Dark Storm Gauntlets",
				350,
				"|cffa335ee|Hitem:21585|h[Dark Storm Gauntlets]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
				"Warlock super-priority",
			},
			{
				"Gauntlets of Annihilation",
				450,
				"|cffa335ee|Hitem:21581|h[Gauntlets of Annihilation]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Metal Rogue",
				},
				"GOLD",
			},
			{
				"Ring of the Godslayer",
				250,
				"|cffa335ee|Hitem:21596|h[Ring of the Godslayer]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Hunter",
				},
				"GOLD",
			},
			{
				"Vanquished Tentacle of C'Thun",
				0,
				"|cffa335ee|Hitem:21579|h[Vanquished Tentacle of C'Thun]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Scepter of the False Prophet",
				500,
				"|cffa335ee|Hitem:21839|h[Scepter of the False Prophet]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Death's Sting",
				600,
				"|cffa335ee|Hitem:21126|h[Death's Sting]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Stabby Rogue",
				},
				"GOLD",
				"Requires dagger commitment",
			},
			{
				"Dark Edge of Insanity",
				0,
				"|cffa335ee|Hitem:21134|h[Dark Edge of Insanity]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Carapace of the Old God",
				"T",
				"|cffa335ee|Hitem:20929|h[Carapace of the Old God]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"GOLD",
				"Tank super-priority",
			},
			{
				"Avenger's Breastplate",
				300,
				"|cffa335ee|Hitem:21389|h[Avenger's Breastplate]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"GOLD",
				[9] = "Carapace of the Old God",
			},
			{
				"Conqueror's Breastplate",
				300,
				"|cffa335ee|Hitem:21331|h[Conqueror's Breastplate]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"GOLD",
				[9] = "Carapace of the Old God",
			},
			{
				"Deathdealer's Vest",
				300,
				"|cffa335ee|Hitem:21364|h[Deathdealer's Vest]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"GOLD",
				[9] = "Carapace of the Old God",
			},
			{
				"Striker's Hauberk",
				300,
				"|cffa335ee|Hitem:21370|h[Striker's Hauberk]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"GOLD",
				[9] = "Carapace of the Old God",
			},
			{
				"Husk of the Old God",
				"T",
				"|cffa335ee|Hitem:20933|h[Husk of the Old God]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Doomcaller's Robes",
				100,
				"|cffa335ee|Hitem:21334|h[Doomcaller's Robes]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"SILVER",
				[9] = "Husk of the Old God",
			},
			{
				"Enigma Robes",
				100,
				"|cffa335ee|Hitem:21343|h[Enigma Robes]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"SILVER",
				[9] = "Husk of the Old God",
			},
			{
				"Genesis Vest",
				100,
				"|cffa335ee|Hitem:21357|h[Genesis Vest]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"SILVER",
				[9] = "Husk of the Old God",
			},
			{
				"Vestments of the Oracle",
				100,
				"|cffa335ee|Hitem:21351|h[Vestments of the Oracle]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"SILVER",
				[9] = "Husk of the Old God",
			},
			{
				"Eye of C'Thun",
				"T",
				"|cffa335ee|Hitem:21221|h[Eye of C'Thun]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Amulet of the Fallen God",
				50,
				"|cffa335ee|Hitem:21712|h[Amulet of the Fallen God]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"SILVER",
				[9] = "Eye of C'Thun",
			},
			{
				"Cloak of the Fallen God",
				150,
				"|cffa335ee|Hitem:21710|h[Cloak of the Fallen God]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"SILVER",
				[9] = "Eye of C'Thun",
			},
			{
				"Ring of the Fallen God",
				250,
				"|cffa335ee|Hitem:21709|h[Ring of the Fallen God]|h|r",
				"Ahn'Qiraj",
				"C'Thun",
				{
				},
				"GOLD",
				[9] = "Eye of C'Thun",
			},
			{
				"Garb of Royal Ascension",
				0,
				"|cffa335ee|Hitem:21838|h[Garb of Royal Ascension]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Progression",
				},
				"GOLD",
			},
			{
				"Gloves of the Immortal",
				0,
				"|cffa335ee|Hitem:21888|h[Gloves of the Immortal]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Gloves of the Redeemed Prophecy",
				0,
				"|cffa335ee|Hitem:21889|h[Gloves of the Redeemed Prophecy]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Neretzek, The Blood Drinker",
				0,
				"|cffa335ee|Hitem:21856|h[Neretzek, The Blood Drinker]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Anubisath Warhammer",
				500,
				"|cffa335ee|Hitem:21837|h[Anubisath Warhammer]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Metal Rogue",
				},
				"GOLD",
				"Emp Demo Prio",
			},
			{
				"Ritssyn's Ring of Chaos",
				250,
				"|cffa335ee|Hitem:21836|h[Ritssyn's Ring of Chaos]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Shard of the Fallen Star",
				0,
				"|cffa335ee|Hitem:21891|h[Shard of the Fallen Star]|h|r",
				"Ahn'Qiraj",
				"Trash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Imperial Qiraji Regalia",
				"T",
				"|cffa335ee|Hitem:21237|h[Imperial Qiraji Regalia]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
					"KAT4FITE",
					"Mage",
					"Priest (Heal)",
					"Warlock",
				},
				"GOLD",
				"Non-Shadow Flame Prio",
			},
			{
				"Blessed Qiraji War Hammer",
				450,
				"|cffa335ee|Hitem:21268|h[Blessed Qiraji War Hammer]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Regalia",
			},
			{
				"Blessed Qiraji Acolyte Staff",
				450,
				"|cffa335ee|Hitem:21273|h[Blessed Qiraji Acolyte Staff]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Regalia",
			},
			{
				"Blessed Qiraji Augur Staff",
				450,
				"|cffa335ee|Hitem:21275|h[Blessed Qiraji Augur Staff]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Regalia",
			},
			{
				"Imperial Qiraji Armaments",
				"T",
				"|cffa335ee|Hitem:21232|h[Imperial Qiraji Armaments]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
					"Stabby Rogue",
				},
				"GOLD",
			},
			{
				"Blessed Qiraji War Axe",
				400,
				"|cffa335ee|Hitem:21242|h[Blessed Qiraji War Axe]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Armaments",
			},
			{
				"Blessed Qiraji Pugio",
				400,
				"|cffa335ee|Hitem:21244|h[Blessed Qiraji Pugio]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Armaments",
			},
			{
				"Blessed Qiraji Musket",
				400,
				"|cffa335ee|Hitem:21272|h[Blessed Qiraji Musket]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Armaments",
			},
			{
				"Blessed Qiraji Bulwark",
				400,
				"|cffa335ee|Hitem:21269|h[Blessed Qiraji Bulwark]|h|r",
				"Ahn'Qiraj",
				"Shared",
				{
				},
				"GOLD",
				[9] = "Imperial Qiraji Armaments",
			},
			{
				"Bindings of Transcendence",
				100,
				"|cffa335ee|Hitem:16926|h[Bindings of Transcendence]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Netherwind Bindings",
				0,
				"|cffa335ee|Hitem:16918|h[Netherwind Bindings]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Nemesis Bracers",
				0,
				"|cffa335ee|Hitem:16934|h[Nemesis Bracers]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Bloodfang Bracers",
				100,
				"|cffa335ee|Hitem:16911|h[Bloodfang Bracers]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Stormrage Bracers",
				100,
				"|cffa335ee|Hitem:16904|h[Stormrage Bracers]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Dragonstalker's Bracers",
				100,
				"|cffa335ee|Hitem:16935|h[Dragonstalker's Bracers]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"Judgement Bindings",
				0,
				"|cffa335ee|Hitem:16951|h[Judgement Bindings]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Bracelets of Wrath",
				100,
				"|cffa335ee|Hitem:16959|h[Bracelets of Wrath]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Arcane Infused Gem",
				0,
				"|cffa335ee|Hitem:19336|h[Arcane Infused Gem]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"The Black Book",
				0,
				"|cffa335ee|Hitem:19337|h[The Black Book]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Mantle of the Blackwing Cabal",
				200,
				"|cffa335ee|Hitem:19370|h[Mantle of the Blackwing Cabal]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
				"Shadow Priest super-priority",
			},
			{
				"Gloves of Rapid Evolution",
				0,
				"|cffa335ee|Hitem:19369|h[Gloves of Rapid Evolution]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Spineshatter",
				70,
				"|cffa335ee|Hitem:19335|h[Spineshatter]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"SILVER",
				"Catch-up",
			},
			{
				"The Untamed Blade",
				0,
				"|cffa335ee|Hitem:19334|h[The Untamed Blade]|h|r",
				"Blackwing Lair",
				"Razorgore the Untamed",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Belt of Transcendence",
				100,
				"|cffa335ee|Hitem:16925|h[Belt of Transcendence]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Netherwind Belt",
				0,
				"|cffa335ee|Hitem:16818|h[Netherwind Belt]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Nemesis Belt",
				0,
				"|cffa335ee|Hitem:16933|h[Nemesis Belt]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Bloodfang Belt",
				100,
				"|cffa335ee|Hitem:16910|h[Bloodfang Belt]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Stormrage Belt",
				0,
				"|cffa335ee|Hitem:16903|h[Stormrage Belt]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Dragonstalker's Belt",
				100,
				"|cffa335ee|Hitem:16936|h[Dragonstalker's Belt]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"Judgement Belt",
				0,
				"|cffa335ee|Hitem:16952|h[Judgement Belt]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Waistband of Wrath",
				100,
				"|cffa335ee|Hitem:16960|h[Waistband of Wrath]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Mind Quickening Gem",
				100,
				"|cffa335ee|Hitem:19339|h[Mind Quickening Gem]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Rune of Metamorphosis",
				0,
				"|cffa335ee|Hitem:19340|h[Rune of Metamorphosis]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Helm of Endless Rage",
				150,
				"|cffa335ee|Hitem:19372|h[Helm of Endless Rage]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Pendant of the Fallen Dragon",
				100,
				"|cffa335ee|Hitem:19371|h[Pendant of the Fallen Dragon]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Red Dragonscale Protector",
				0,
				"|cffa335ee|Hitem:19348|h[Red Dragonscale Protector]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Dragonfang Blade",
				70,
				"|cffa335ee|Hitem:19346|h[Dragonfang Blade]|h|r",
				"Blackwing Lair",
				"Vaelastraz the Corrupt",
				{
					"Hunter",
					"Stabby Rogue",
					"Tank",
				},
				"SILVER",
				"Catch-up",
			},
			{
				"Boots of Transcendence",
				50,
				"|cffa335ee|Hitem:16919|h[Boots of Transcendence]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Nemesis Boots",
				0,
				"|cffa335ee|Hitem:16927|h[Nemesis Boots]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Netherwind Boots",
				0,
				"|cffa335ee|Hitem:16912|h[Netherwind Boots]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Bloodfang Boots",
				50,
				"|cffa335ee|Hitem:16906|h[Bloodfang Boots]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Slicey Rogue",
				},
				"SILVER",
			},
			{
				"Stormrage Boots",
				50,
				"|cffa335ee|Hitem:16898|h[Stormrage Boots]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Dragonstalker's Greaves",
				150,
				"|cffa335ee|Hitem:16941|h[Dragonstalker's Greaves]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"Judgement Sabatons",
				0,
				"|cffa335ee|Hitem:16957|h[Judgement Sabatons]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Sabatons of Wrath",
				150,
				"|cffa335ee|Hitem:16965|h[Sabatons of Wrath]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Lifegiving Gem",
				200,
				"|cffa335ee|Hitem:19341|h[Lifegiving Gem]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Venomous Totem",
				0,
				"|cffa335ee|Hitem:19342|h[Venomous Totem]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Black Brood Pauldrons",
				0,
				"|cffa335ee|Hitem:19373|h[Black Brood Pauldrons]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Bracers of Arcane Accuracy",
				200,
				"|cffa335ee|Hitem:19374|h[Bracers of Arcane Accuracy]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Heartstriker",
				100,
				"|cffa335ee|Hitem:19350|h[Heartstriker]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Maladath, Runed Blade of the Black Flight",
				200,
				"|cffa335ee|Hitem:19351|h[Maladath, Runed Blade of the Black Flight]|h|r",
				"Blackwing Lair",
				"Broodlord Lashlayer",
				{
					"Metal Rogue",
					"Tank",
				},
				"SILVER",
				"Non-Human Rogues also",
			},
			{
				"Handguards of Transcendence",
				80,
				"|cffa335ee|Hitem:16920|h[Handguards of Transcendence]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Netherwind Gloves",
				0,
				"|cffa335ee|Hitem:16913|h[Netherwind Gloves]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Nemesis Gloves",
				0,
				"|cffa335ee|Hitem:16928|h[Nemesis Gloves]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Bloodfang Gloves",
				50,
				"|cffa335ee|Hitem:16907|h[Bloodfang Gloves]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Slicey Rogue",
				},
				"SILVER",
				"P5 cost: 200",
			},
			{
				"Stormrage Handguards",
				150,
				"|cffa335ee|Hitem:16899|h[Stormrage Handguards]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Dragonstalker's Gauntlets",
				150,
				"|cffa335ee|Hitem:16940|h[Dragonstalker's Gauntlets]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"Judgement Gauntlets",
				0,
				"|cffa335ee|Hitem:16956|h[Judgement Gauntlets]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Gauntlets of Wrath",
				150,
				"|cffa335ee|Hitem:16964|h[Gauntlets of Wrath]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Drake Talon Pauldrons",
				250,
				"|cffa335ee|Hitem:19394|h[Drake Talon Pauldrons]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Metal Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Taut Dragonhide Belt",
				0,
				"|cffa335ee|Hitem:19396|h[Taut Dragonhide Belt]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Drake Talon Cleaver",
				0,
				"|cffa335ee|Hitem:19353|h[Drake Talon Cleaver]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Shadow Wing Focus Staff",
				70,
				"|cffa335ee|Hitem:19355|h[Shadow Wing Focus Staff]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Druid (Heal)",
					"Mage",
					"Warlock",
				},
				"SILVER",
				"Catch-up",
			},
			{
				"Ring of Blackrock",
				100,
				"|cffa335ee|Hitem:19397|h[Ring of Blackrock]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
					"Priest (Shadow)",
				},
				"SILVER",
			},
			{
				"Rejuvenating Gem",
				400,
				"|cffa335ee|Hitem:19395|h[Rejuvenating Gem]|h|r",
				"Blackwing Lair",
				"Firemaw, Ebonroc, Flamegor",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Scrolls of Blinding Light",
				0,
				"|cffa335ee|Hitem:19343|h[Scrolls of Blinding Light]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Cloak of Firemaw",
				150,
				"|cffa335ee|Hitem:19398|h[Cloak of Firemaw]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Black Ash Robe",
				0,
				"|cffa335ee|Hitem:19399|h[Black Ash Robe]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Firemaw's Clutch",
				200,
				"|cffa335ee|Hitem:19400|h[Firemaw's Clutch]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Mage",
					"Priest (Shadow)",
				},
				"SILVER",
				"Shadow Priest super-priority",
			},
			{
				"Primalist's Linked Legguards",
				0,
				"|cffa335ee|Hitem:19401|h[Primalist's Linked Legguards]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Legguards of the Fallen Crusader",
				100,
				"|cffa335ee|Hitem:19402|h[Legguards of the Fallen Crusader]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Metal Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Claw of the Black Drake",
				0,
				"|cffa335ee|Hitem:19365|h[Claw of the Black Drake]|h|r",
				"Blackwing Lair",
				"Firemaw",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Ebony Flame Gloves",
				200,
				"|cffa335ee|Hitem:19407|h[Ebony Flame Gloves]|h|r",
				"Blackwing Lair",
				"Ebonroc",
				{
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Malfurion's Blessed Bulwark",
				150,
				"|cffa335ee|Hitem:19405|h[Malfurion's Blessed Bulwark]|h|r",
				"Blackwing Lair",
				"Ebonroc",
				{
					"KAT4FITE",
					"Metal Rogue",
				},
				"SILVER",
				"Feral Druid super-priority",
			},
			{
				"Dragonbreath Hand Cannon",
				100,
				"|cffa335ee|Hitem:19368|h[Dragonbreath Hand Cannon]|h|r",
				"Blackwing Lair",
				"Ebonroc",
				{
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Band of Forced Concentration",
				250,
				"|cffa335ee|Hitem:19403|h[Band of Forced Concentration]|h|r",
				"Blackwing Lair",
				"Ebonroc",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Aegis of Preservation",
				0,
				"|cffa335ee|Hitem:19345|h[Aegis of Preservation]|h|r",
				"Blackwing Lair",
				"Ebonroc",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Drake Fang Talisman",
				400,
				"|cffa335ee|Hitem:19406|h[Drake Fang Talisman]|h|r",
				"Blackwing Lair",
				"Ebonroc",
				{
					"KAT4FITE",
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"GOLD",
				"Feral Druid prio unlocks after 4 drops",
			},
			{
				"Shroud of Pure Thought",
				100,
				"|cffa335ee|Hitem:19430|h[Shroud of Pure Thought]|h|r",
				"Blackwing Lair",
				"Flamegor",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Emberweave Leggings",
				0,
				"|cffa335ee|Hitem:19433|h[Emberweave Leggings]|h|r",
				"Blackwing Lair",
				"Flamegor",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Dragon's Touch",
				0,
				"|cffa335ee|Hitem:19367|h[Dragon's Touch]|h|r",
				"Blackwing Lair",
				"Flamegor",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Herald of Woe",
				0,
				"|cffa335ee|Hitem:19357|h[Herald of Woe]|h|r",
				"Blackwing Lair",
				"Flamegor",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Circle of Applied Force",
				200,
				"|cffa335ee|Hitem:19432|h[Circle of Applied Force]|h|r",
				"Blackwing Lair",
				"Flamegor",
				{
					"KAT4FITE",
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Styleen's Impeding Scarab",
				325,
				"|cffa335ee|Hitem:19431|h[Styleen's Impeding Scarab]|h|r",
				"Blackwing Lair",
				"Flamegor",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Pauldrons of Transcendence",
				150,
				"|cffa335ee|Hitem:16924|h[Pauldrons of Transcendence]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Netherwind Mantle",
				80,
				"|cffa335ee|Hitem:16917|h[Netherwind Mantle]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Nemesis Spaulders",
				125,
				"|cffa335ee|Hitem:16932|h[Nemesis Spaulders]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Bloodfang Spaulders",
				50,
				"|cffa335ee|Hitem:16832|h[Bloodfang Spaulders]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Slicey Rogue",
				},
				"SILVER",
			},
			{
				"Stormrage Pauldrons",
				0,
				"|cffa335ee|Hitem:16902|h[Stormrage Pauldrons]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Dragonstalker's Spaulders",
				200,
				"|cffa335ee|Hitem:16937|h[Dragonstalker's Spaulders]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"Judgement Spaulders",
				0,
				"|cffa335ee|Hitem:16953|h[Judgement Spaulders]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Pauldrons of Wrath",
				200,
				"|cffa335ee|Hitem:16961|h[Pauldrons of Wrath]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Taut Dragonhide Shoulderpads",
				100,
				"|cffa335ee|Hitem:19389|h[Taut Dragonhide Shoulderpads]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"KAT4FITE",
				},
				"SILVER",
			},
			{
				"Elementium Threaded Cloak",
				150,
				"|cffa335ee|Hitem:19386|h[Elementium Threaded Cloak]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"KAT4FITE",
					"Tank",
				},
				"SILVER",
			},
			{
				"Taut Dragonhide Gloves",
				80,
				"|cffa335ee|Hitem:19390|h[Taut Dragonhide Gloves]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Angelista's Grasp",
				0,
				"|cffa335ee|Hitem:19388|h[Angelista's Grasp]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Girdle of the Fallen Crusader",
				0,
				"|cffa335ee|Hitem:19392|h[Girdle of the Fallen Crusader]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Empowered Leggings",
				200,
				"|cffa335ee|Hitem:19385|h[Empowered Leggings]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Shimmering Geta",
				100,
				"|cffa335ee|Hitem:19391|h[Shimmering Geta]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Chromatic Boots",
				225,
				"|cffa335ee|Hitem:19387|h[Chromatic Boots]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Metal Rogue",
				},
				"GOLD",
			},
			{
				"Ashjre'thul, Crossbow of Smiting",
				400,
				"|cffa335ee|Hitem:19361|h[Ashjre'thul, Crossbow of Smiting]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Hunter",
				},
				"GOLD",
			},
			{
				"Elementium Reinforced Bulwark",
				250,
				"|cffa335ee|Hitem:19349|h[Elementium Reinforced Bulwark]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Claw of Chromaggus",
				300,
				"|cffa335ee|Hitem:19347|h[Claw of Chromaggus]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Mage",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Chromatically Tempered Sword",
				500,
				"|cffa335ee|Hitem:19352|h[Chromatically Tempered Sword]|h|r",
				"Blackwing Lair",
				"Chromaggus",
				{
					"Metal Rogue",
					"Slicey Rogue",
				},
				"GOLD",
			},
			{
				"Robes of Transcendence",
				200,
				"|cffa335ee|Hitem:16923|h[Robes of Transcendence]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Netherwind Robes",
				0,
				"|cffa335ee|Hitem:16916|h[Netherwind Robes]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Nemesis Robes",
				0,
				"|cffa335ee|Hitem:16931|h[Nemesis Robes]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Warlock",
				},
				"SILVER",
			},
			{
				"Bloodfang Chestpiece",
				200,
				"|cffa335ee|Hitem:16905|h[Bloodfang Chestpiece]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Stormrage Chestguard",
				0,
				"|cffa335ee|Hitem:16897|h[Stormrage Chestguard]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Druid (Heal)",
				},
				"SILVER",
			},
			{
				"Dragonstalker's Breastplate",
				200,
				"|cffa335ee|Hitem:16942|h[Dragonstalker's Breastplate]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Hunter",
				},
				"SILVER",
			},
			{
				"Judgement Breastplate",
				0,
				"|cffa335ee|Hitem:16958|h[Judgement Breastplate]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Breastplate of Wrath",
				200,
				"|cffa335ee|Hitem:16966|h[Breastplate of Wrath]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Tank",
				},
				"SILVER",
			},
			{
				"Head of Nefarian",
				"T",
				"|cffa335ee|Hitem:19003|h[Head of Nefarian]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Hunter",
					"KAT4FITE",
					"Metal Rogue",
					"Slicey Rogue",
					"Stabby Rogue",
					"Tank",
				},
				"SILVER",
				"Prio for casters with BWL 1H as well",
			},
			{
				"Master Dragonslayer's Medallion",
				150,
				"|cffa335ee|Hitem:19383|h[Master Dragonslayer's Medallion]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
				},
				"SILVER",
				[9] = "Head of Nefarian",
			},
			{
				"Master Dragonslayer's Ring",
				150,
				"|cffa335ee|Hitem:19384|h[Master Dragonslayer's Ring]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
				},
				"SILVER",
				[9] = "Head of Nefarian",
			},
			{
				"Master Dragonslayer's Orb",
				0,
				"|cffa335ee|Hitem:19366|h[Master Dragonslayer's Orb]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
				},
				"SILVER",
				[9] = "Head of Nefarian",
			},
			{
				"Lok'amir il Romathis",
				400,
				"|cffa335ee|Hitem:19360|h[Lok'amir il Romathis]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Shadow)",
				},
				"SILVER",
			},
			{
				"Crul'shorukh, Edge of Chaos",
				400,
				"|cffa335ee|Hitem:19363|h[Crul'shorukh, Edge of Chaos]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Ashkandi, Greatsword of the Brotherhood",
				0,
				"|cffa335ee|Hitem:19364|h[Ashkandi, Greatsword of the Brotherhood]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Staff of the Shadow Flame",
				450,
				"|cffa335ee|Hitem:19356|h[Staff of the Shadow Flame]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Mage",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Mish'undare, Circlet of the Mind Flayer",
				250,
				"|cffa335ee|Hitem:19375|h[Mish'undare, Circlet of the Mind Flayer]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Mage",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Prestor's Talisman of Connivery",
				150,
				"|cffa335ee|Hitem:19377|h[Prestor's Talisman of Connivery]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Hunter",
					"KAT4FITE",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"GOLD",
			},
			{
				"Cloak of the Brood Lord",
				0,
				"|cffa335ee|Hitem:19378|h[Cloak of the Brood Lord]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Therazane's Link",
				0,
				"|cffa335ee|Hitem:19380|h[Therazane's Link]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Boots of the Shadow Flame",
				200,
				"|cffa335ee|Hitem:19381|h[Boots of the Shadow Flame]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"KAT4FITE",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Archimtiros' Ring of Reckoning",
				125,
				"|cffa335ee|Hitem:19376|h[Archimtiros' Ring of Reckoning]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"KAT4FITE",
					"Tank",
				},
				"SILVER",
			},
			{
				"Pure Elementium Band",
				150,
				"|cffa335ee|Hitem:19382|h[Pure Elementium Band]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Druid (Heal)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Neltharion's Tear",
				400,
				"|cffa335ee|Hitem:19379|h[Neltharion's Tear]|h|r",
				"Blackwing Lair",
				"Nefarian",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"GOLD",
			},
			{
				"Cloak of Draconic Might",
				150,
				"|cffa335ee|Hitem:19436|h[Cloak of Draconic Might]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"KAT4FITE",
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Interlaced Shadow Jerkin",
				0,
				"|cffa335ee|Hitem:19439|h[Interlaced Shadow Jerkin]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Boots of Pure Thought",
				150,
				"|cffa335ee|Hitem:19437|h[Boots of Pure Thought]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"GOLD",
			},
			{
				"Ringo's Blizzard Boots",
				250,
				"|cffa335ee|Hitem:19438|h[Ringo's Blizzard Boots]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Mage",
				},
				"SILVER",
			},
			{
				"Band of Dark Dominion",
				200,
				"|cffa335ee|Hitem:19434|h[Band of Dark Dominion]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Essence Gatherer",
				100,
				"|cffa335ee|Hitem:19435|h[Essence Gatherer]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Doom's Edge",
				100,
				"|cffa335ee|Hitem:19362|h[Doom's Edge]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Hunter",
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Draconic Avenger",
				0,
				"|cffa335ee|Hitem:19354|h[Draconic Avenger]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Draconic Maul",
				300,
				"|cffa335ee|Hitem:19358|h[Draconic Maul]|h|r",
				"Blackwing Lair",
				"Trash",
				{
					"KAT4FITE",
				},
				"SILVER",
			},
			{
				"Green Dragonskin Cloak",
				0,
				"|cffa335ee|Hitem:20579|h[Green Dragonskin Cloak]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Dragonspur Wraps",
				0,
				"|cffa335ee|Hitem:20615|h[Dragonspur Wraps]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Dragonbone Wristguards",
				0,
				"|cffa335ee|Hitem:20616|h[Dragonbone Wristguards]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Gloves of Delusional Power",
				0,
				"|cffa335ee|Hitem:20618|h[Gloves of Delusional Power]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Ancient Corroded Leggings",
				0,
				"|cffa335ee|Hitem:20617|h[Ancient Corroded Leggings]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Acid Inscribed Greaves",
				0,
				"|cffa335ee|Hitem:20619|h[Acid Inscribed Greaves]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Trance Stone",
				0,
				"|cffa335ee|Hitem:20582|h[Trance Stone]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Druid (Heal)",
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Hammer of Bestial Fury",
				250,
				"|cffa335ee|Hitem:20580|h[Hammer of Bestial Fury]|h|r",
				"Green Dragons",
				"Shared",
				{
					"KAT4FITE",
				},
				"SILVER",
			},
			{
				"Staff of Rampant Growth",
				0,
				"|cffa335ee|Hitem:20581|h[Staff of Rampant Growth]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Malfurion's Signet Ring",
				0,
				"|cffa335ee|Hitem:20600|h[Malfurion's Signet Ring]|h|r",
				"Green Dragons",
				"Shared",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Deviate Growth Cap",
				250,
				"|cffa335ee|Hitem:20628|h[Deviate Growth Cap]|h|r",
				"Green Dragons",
				"Lethon",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
				},
				"GOLD",
			},
			{
				"Black Bark Wristbands",
				75,
				"|cffa335ee|Hitem:20626|h[Black Bark Wristbands]|h|r",
				"Green Dragons",
				"Lethon",
				{
					"Mage",
					"Priest (Shadow)",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Gauntlets of the Shining Light",
				0,
				"|cffa335ee|Hitem:20630|h[Gauntlets of the Shining Light]|h|r",
				"Green Dragons",
				"Lethon",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Belt of the Dark Bog",
				0,
				"|cffa335ee|Hitem:20625|h[Belt of the Dark Bog]|h|r",
				"Green Dragons",
				"Lethon",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Dark Heart Pants",
				150,
				"|cffa335ee|Hitem:20627|h[Dark Heart Pants]|h|r",
				"Green Dragons",
				"Lethon",
				{
					"KAT4FITE",
					"Metal Rogue",
				},
				"SILVER",
			},
			{
				"Malignant Footguards",
				0,
				"|cffa335ee|Hitem:20629|h[Malignant Footguards]|h|r",
				"Green Dragons",
				"Lethon",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Circlet of Restless Dreams",
				150,
				"|cffa335ee|Hitem:20623|h[Circlet of Restless Dreams]|h|r",
				"Green Dragons",
				"Emeriss",
				{
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Dragonheart Necklace",
				0,
				"|cffa335ee|Hitem:20622|h[Dragonheart Necklace]|h|r",
				"Green Dragons",
				"Emeriss",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Ring of the Unliving",
				80,
				"|cffa335ee|Hitem:20624|h[Ring of the Unliving]|h|r",
				"Green Dragons",
				"Emeriss",
				{
					"Hunter",
					"KAT4FITE",
					"Slicey Rogue",
					"Stabby Rogue",
				},
				"SILVER",
			},
			{
				"Boots of the Endless Moor",
				0,
				"|cffa335ee|Hitem:20621|h[Boots of the Endless Moor]|h|r",
				"Green Dragons",
				"Emeriss",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Polished Ironwood Crossbow",
				0,
				"|cffa335ee|Hitem:20599|h[Polished Ironwood Crossbow]|h|r",
				"Green Dragons",
				"Emeriss",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Unnatural Leather Spaulders",
				0,
				"|cffa335ee|Hitem:20633|h[Unnatural Leather Spaulders]|h|r",
				"Green Dragons",
				"Taerar",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Mendicant's Slippers",
				80,
				"|cffa335ee|Hitem:20631|h[Mendicant's Slippers]|h|r",
				"Green Dragons",
				"Taerar",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Boots of Fright",
				80,
				"|cffa335ee|Hitem:20634|h[Boots of Fright]|h|r",
				"Green Dragons",
				"Taerar",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
				},
				"SILVER",
			},
			{
				"Mindtear Band",
				250,
				"|cffa335ee|Hitem:20632|h[Mindtear Band]|h|r",
				"Green Dragons",
				"Taerar",
				{
					"Mage",
					"Warlock",
				},
				"SILVER",
			},
			{
				"Nightmare Blade",
				150,
				"|cffa335ee|Hitem:20577|h[Nightmare Blade]|h|r",
				"Green Dragons",
				"Taerar",
				{
					"Metal Rogue",
					"Slicey Rogue",
					"Tank",
				},
				"SILVER",
			},
			{
				"Acid Inscribed Pauldrons",
				0,
				"|cffa335ee|Hitem:20637|h[Acid Inscribed Pauldrons]|h|r",
				"Green Dragons",
				"Ysondre",
				{
					"Progression",
				},
				"SILVER",
			},
			{
				"Jade Inlaid Vestments",
				0,
				"|cffa335ee|Hitem:20635|h[Jade Inlaid Vestments]|h|r",
				"Green Dragons",
				"Ysondre",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Leggings of the Demented Mind",
				0,
				"|cffa335ee|Hitem:20638|h[Leggings of the Demented Mind]|h|r",
				"Green Dragons",
				"Ysondre",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Strangely Glyphed Legplates",
				0,
				"|cffa335ee|Hitem:20639|h[Strangely Glyphed Legplates]|h|r",
				"Green Dragons",
				"Ysondre",
				{
					"Garbage",
				},
				"SILVER",
			},
			{
				"Hibernation Crystal",
				150,
				"|cffa335ee|Hitem:20636|h[Hibernation Crystal]|h|r",
				"Green Dragons",
				"Ysondre",
				{
					"Druid (Heal)",
					"Paladin (Holy)",
					"Priest (Heal)",
				},
				"SILVER",
			},
			{
				"Emerald Dragonfang",
				100,
				"|cffa335ee|Hitem:20578|h[Emerald Dragonfang]|h|r",
				"Green Dragons",
				"Ysondre",
				{
					"Stabby Rogue",
				},
				"SILVER",
			},
		},
	},
	history = {
		timestamp = 1596567505,
		data = {},
	},
};

function ABGP:CheckHardcodedData()
	for key, initialData in pairs(self.initialData) do
		_G.ABGP_Data2[key] = _G.ABGP_Data2[key] or { timestamp = 0, data = {} };

		if _G.ABGP_Data2[key].timestamp < initialData.timestamp then
			_G.ABGP_Data2[key].timestamp = initialData.timestamp;
			_G.ABGP_Data2[key].data = self.tCopy(initialData.data);
		end
	end
end
