name: Package AddOn

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull source
      uses: actions/checkout@v1
      
    - name: Create a zip for the release
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./${GITHUB_REPOSITORY##*/}${GITHUB_REF##*/}.zip .

    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: ${GITHUB_REPOSITORY##*/}${GITHUB_REF##*/}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
