name: Package AddOn

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull source
      uses: actions/checkout@v1

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Create a zip for the release
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: ABGP-${{ steps.get_version.outputs.VERSION }}.zip
        exclusions: '*.git*'
        path: ABGP

    - name: Upload to release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: ABGP-${{ steps.get_version.outputs.VERSION }}.zip
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
